/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electronegatividad;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.HashMap;
import javax.print.attribute.HashAttributeSet;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class Electronegatividad_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form Electronegatividad_Frame_01
     */
    public Electronegatividad_Frame_01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonAcercade = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSimboloUno = new javax.swing.JTextField();
        jTextFieldSimboloDos = new javax.swing.JTextField();
        jTextFieldSimboloTres = new javax.swing.JTextField();
        jTextFieldSimboloCuatro = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldResultado = new javax.swing.JTextField();
        jTextFieldPorcentaje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo de Electronegatividad");
        setMinimumSize(new java.awt.Dimension(860, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 2, 2));
        jLabel1.setText("Química");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 2, 2));
        jLabel2.setText("Electronegatividad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(4, 2, 2));
        jButton1.setText("Tabla de electronegatividad");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(150, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 236, 50));

        jButtonAcercade.setForeground(new java.awt.Color(4, 2, 2));
        jButtonAcercade.setText("Créditos");
        jButtonAcercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcercadeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 112, 39));

        jButton4.setForeground(new java.awt.Color(4, 2, 2));
        jButton4.setText("Salir");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 570, 114, 39));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 2, 2));
        jLabel3.setText("¿Qué es la electronegatividad?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jButton6.setForeground(new java.awt.Color(4, 2, 2));
        jButton6.setText("Diferencia de electronegatividad");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setMaximumSize(new java.awt.Dimension(200, 25));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 236, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 2, 2));
        jLabel4.setText("Cálculo de diferencia de electronegatividad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 560, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(4, 2, 2));
        jButton2.setText("Conceptos básicos");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 236, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 2, 2));
        jLabel5.setText("La electronegatividad es una medida de la cantidad de fuerza con la que un átomo atrae los electrones en un enlace. Un ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 2, 2));
        jLabel6.setText("átomo con una electronegatividad alta atrae electrones con mucha fuerza, mientras que uno con una electronegatividad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(4, 2, 2));
        jLabel7.setText("baja los atrae débilmente.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel8.setForeground(new java.awt.Color(4, 2, 2));
        jLabel8.setText("Escribe los elementos químicos presentes en la reacción química:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jTextFieldSimboloUno.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jTextFieldSimboloUno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldSimboloUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 50, 40));

        jTextFieldSimboloDos.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jTextFieldSimboloDos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldSimboloDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 50, 40));

        jTextFieldSimboloTres.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jTextFieldSimboloTres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldSimboloTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 50, 40));

        jTextFieldSimboloCuatro.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jTextFieldSimboloCuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldSimboloCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 50, 40));

        jButtonCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCalcular.setForeground(new java.awt.Color(4, 2, 2));
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 181, 46));

        jButtonLimpiar.setForeground(new java.awt.Color(4, 2, 2));
        jButtonLimpiar.setText("Nuevos datos");
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 180, 30));

        jLabel9.setForeground(new java.awt.Color(4, 2, 2));
        jLabel9.setText("Resultado ΔEn");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jTextFieldResultado.setEditable(false);
        getContentPane().add(jTextFieldResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 100, 29));

        jTextFieldPorcentaje.setEditable(false);
        jTextFieldPorcentaje.setForeground(new java.awt.Color(4, 2, 2));
        getContentPane().add(jTextFieldPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 100, 30));

        jLabel11.setForeground(new java.awt.Color(4, 2, 2));
        jLabel11.setText("Porcentaje de ΔEn");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel12.setText("Recuerda escribir los elementos de acuerdo con la tabla periódica.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronegatividad/imagen/AtomoQuimica.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -40, 1670, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tabla tab = new tabla();
        tab.setVisible(true);
        this.dispose();    //abre la tabla de electronegatividad;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Diferencia tab = new Diferencia();
        tab.setVisible(true);
        this.dispose(); // abre la tabla de porcentaje de electronegatividad
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();        //cierra todo
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        if (jTextFieldSimboloUno.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "¡Ingresalo desde la primera casilla");
            return;
        }

        if (jTextFieldSimboloUno.getText().length() == 0 && jTextFieldSimboloDos.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "¡Las Celdas estan Vacias!");
            return;

        }
        if (jTextFieldSimboloDos.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "¡Ingresa el segundo elemento en la segunda casilla!");
            return;

        }

        if (jTextFieldSimboloDos.getText().length() == 0 && jTextFieldSimboloTres.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "¡Ingresa más de un elemento," + "\n" + "si quieres ver la electronegatividad del elmento "
                    + "puedes revisarlo en la tabla de electronegatividad");
            return;
        }

        Double resultado, resultadoparcial;

        HashMap<String, Double> tablaPeriodica = new HashMap<>();

        tablaPeriodica.put("H", 2.1);
        tablaPeriodica.put("Li", 1.0);
        tablaPeriodica.put("Be", 1.5);
        tablaPeriodica.put("Na", 0.9);
        tablaPeriodica.put("Mg", 1.2);
        tablaPeriodica.put("K", 0.8);
        tablaPeriodica.put("Ca", 1.0);
        tablaPeriodica.put("Sc", 1.3);
        tablaPeriodica.put("Ti", 1.5);
        tablaPeriodica.put("V", 1.6);
        tablaPeriodica.put("Cr", 1.6);
        tablaPeriodica.put("Mn", 1.5);
        tablaPeriodica.put("Fe", 1.8);
        tablaPeriodica.put("Co", 1.9);
        tablaPeriodica.put("Ni", 1.8);
        tablaPeriodica.put("Cu", 1.9);
        tablaPeriodica.put("Zn", 1.6);
        tablaPeriodica.put("Ga", 1.6);
        tablaPeriodica.put("Ge", 1.8);
        tablaPeriodica.put("As", 2.0);
        tablaPeriodica.put("Se", 2.4);
        tablaPeriodica.put("Br", 2.8);
        tablaPeriodica.put("B", 2.0);
        tablaPeriodica.put("C", 2.5);
        tablaPeriodica.put("N", 3.0);
        tablaPeriodica.put("O", 3.5);
        tablaPeriodica.put("F", 4.0);
        tablaPeriodica.put("Al", 1.5);
        tablaPeriodica.put("Si", 1.8);
        tablaPeriodica.put("P", 2.1);
        tablaPeriodica.put("S", 2.5);
        tablaPeriodica.put("Cl", 3.0);
        tablaPeriodica.put("Rb", 0.8);
        tablaPeriodica.put("Sr", 1.0);
        tablaPeriodica.put("Y", 1.2);
        tablaPeriodica.put("Zr", 1.4);
        tablaPeriodica.put("Nb", 1.6);
        tablaPeriodica.put("Mo", 1.8);
        tablaPeriodica.put("Tc", 1.9);
        tablaPeriodica.put("Ru", 2.2);
        tablaPeriodica.put("Rh", 2.2);
        tablaPeriodica.put("Pd", 2.2);
        tablaPeriodica.put("Ag", 1.9);
        tablaPeriodica.put("Cd", 1.7);
        tablaPeriodica.put("In", 1.7);
        tablaPeriodica.put("Sn", 1.8);
        tablaPeriodica.put("Sb", 1.9);
        tablaPeriodica.put("Te", 2.1);
        tablaPeriodica.put("I", 2.5);
        tablaPeriodica.put("Cs", 0.7);
        tablaPeriodica.put("Ba", 0.9);
        tablaPeriodica.put("Hf", 1.3);
        tablaPeriodica.put("Ta", 1.5);
        tablaPeriodica.put("W", 1.7);
        tablaPeriodica.put("Re", 1.9);
        tablaPeriodica.put("Os", 2.2);
        tablaPeriodica.put("Ir", 2.2);
        tablaPeriodica.put("Pt", 2.2);
        tablaPeriodica.put("Au", 2.4);
        tablaPeriodica.put("Hg", 1.9);
        tablaPeriodica.put("Tl", 1.8);
        tablaPeriodica.put("Pb", 1.9);
        tablaPeriodica.put("Bi", 1.9);
        tablaPeriodica.put("Po", 2.0);
        tablaPeriodica.put("At", 2.2);
        tablaPeriodica.put("Fr", 0.7);
        tablaPeriodica.put("Ra", 0.9);

        String simboloUno = jTextFieldSimboloUno.getText();
        Double valorUno = null;
        if (tablaPeriodica.containsKey(simboloUno)) {
            valorUno = tablaPeriodica.get(simboloUno);

        } else {
            JOptionPane.showMessageDialog(this, "¡Incorrecto! Elemento no existente en la tabla periódica");
            return;
        }
        String simboloDos = jTextFieldSimboloDos.getText();
        Double ValorDos = null;
        if (tablaPeriodica.containsKey(simboloDos)) {
            ValorDos = tablaPeriodica.get(simboloDos);
        } else {
            JOptionPane.showMessageDialog(this, "¡Incorrecto! Elemento no existente en la tabla periódica");
            return;
        }

        String simboloTres = jTextFieldSimboloTres.getText();
        Double ValorTres = 0.0;
        resultadoparcial = 0.0;
        resultado = 0.0;

        if (tablaPeriodica.containsKey(simboloTres)) {
            ValorTres = tablaPeriodica.get(simboloTres);    //Evalua los texField para sacar los valores de electronegatividad
        }
        if (jTextFieldSimboloTres.getText().length() == 0) {
            ValorTres = 0.0;
        } else {
            JOptionPane.showMessageDialog(this, "¡Incorrecto! Elemento no existente en la tabla periódica");
            return;
        }

        String simboloCuatro = jTextFieldSimboloCuatro.getText();
        Double ValorCuatro = 0.0;

        if (tablaPeriodica.containsKey(simboloCuatro)) {
            ValorCuatro = tablaPeriodica.get(simboloCuatro);    //Evalua los texField para sacar los valores de electronegatividad
        }
        if (jTextFieldSimboloCuatro.getText().length() == 0) {
            ValorCuatro = 0.0;
        } else {
            JOptionPane.showMessageDialog(this, "¡Incorrecto! Elemento no existente en la tabla periódica");
            return;
        }

        double b[] = {valorUno, ValorDos, ValorTres, ValorCuatro};

        for (int i = 0; i < b.length; i++) {
            for (int j = 0; j < b.length - 1; j++) {
                if (b[j] > b[j + 1]) {
                    double aux = b[j];
                    b[j] = b[j + 1];
                    b[j + 1] = aux;
                }
            }
        }
        /* for (int i=0;i<b.length; i++){

            System.out.print((b)[i]+" - ");

        }
         */
        double x, y, z, u;
        x = b[0];
        y = b[1];
        z = b[2];
        u = b[3];

        double resultadoParcial2, resultadofin;
        resultadoparcial = u - z;
        if (resultadoparcial > y) {
            resultadoParcial2 = resultadoparcial - y;
        } else {
            resultadoParcial2 = y - resultadoparcial;
        }
        if (resultadoParcial2 > x) {
            resultadofin = resultadoParcial2 - x;
        } else {
            resultadofin = x - resultadoParcial2;
        }

        resultado = resultadofin;

        BigDecimal bigDecimal = new BigDecimal(resultado).setScale(1, RoundingMode.HALF_UP);   //REDONDEAR A UN DECIMAL
        String resultadoparaporcentaje;

        resultadoparaporcentaje = bigDecimal.toString();
        Double resultadofinal = Double.parseDouble(resultadoparaporcentaje);       //PARA PODER CONVERTIRLO A DOUBLE Y COMPARAR

        if (resultadofinal == 0.1) {

            jTextFieldPorcentaje.setText("0.5 %");
        }
        if (resultadofinal == 0.2) {
            jTextFieldPorcentaje.setText("1 %");
        }
        if (resultadofinal == 0.3) {
            jTextFieldPorcentaje.setText("2 %");
        }
        if (resultadofinal == 0.4) {
            jTextFieldPorcentaje.setText("4 %");
        }
        if (resultadofinal == 0.5) {
            jTextFieldPorcentaje.setText("6 %");
        }
        if (resultadofinal == 0.6) {
            jTextFieldPorcentaje.setText("9 %");
        }
        if (resultadofinal == 0.7) {
            jTextFieldPorcentaje.setText("12 %");
        }
        if (resultadofinal == 0.8) {
            jTextFieldPorcentaje.setText("15 %");
        }
        if (resultadofinal == 0.9) {
            jTextFieldPorcentaje.setText("19 %");
        }
        if (resultadofinal == 1.0) {
            jTextFieldPorcentaje.setText("22 %");
        }
        if (resultadofinal == 1.1) {
            jTextFieldPorcentaje.setText("26 %");
        }
        if (resultadofinal == 1.2) {
            jTextFieldPorcentaje.setText("30 %");
        }
        if (resultadofinal == 1.3) {
            jTextFieldPorcentaje.setText("34 %");
        }
        if (resultadofinal == 1.4) {
            jTextFieldPorcentaje.setText("39 %");
        }
        if (resultadofinal == 1.5) {
            jTextFieldPorcentaje.setText("43 %");
        }
        if (resultadofinal == 1.6) {
            jTextFieldPorcentaje.setText("47 %");
        }
        if (resultadofinal == 1.7) {
            jTextFieldPorcentaje.setText("51 %");
        }
        if (resultadofinal == 1.8) {
            jTextFieldPorcentaje.setText("55 %");
        }
        if (resultadofinal == 1.9) {
            jTextFieldPorcentaje.setText("59 %");
        }
        if (resultadofinal == 2.0) {
            jTextFieldPorcentaje.setText("63 %");
        }
        if (resultadofinal == 2.1) {
            jTextFieldPorcentaje.setText("67 %");
        }
        if (resultadofinal == 2.2) {
            jTextFieldPorcentaje.setText("70 %");
        }
        if (resultadofinal == 2.3) {
            jTextFieldPorcentaje.setText("74 %");
        }
        if (resultadofinal == 2.4) {
            jTextFieldPorcentaje.setText("76 %");
        }
        if (resultadofinal == 2.5) {
            jTextFieldPorcentaje.setText("79 %");
        }
        if (resultadofinal == 2.6) {
            jTextFieldPorcentaje.setText("82 %");
        }
        if (resultadofinal == 2.7) {
            jTextFieldPorcentaje.setText("84 %");
        }
        if (resultadofinal == 2.8) {
            jTextFieldPorcentaje.setText("86 %");
        }
        if (resultadofinal == 2.9) {
            jTextFieldPorcentaje.setText("88 %");
        }
        if (resultadofinal == 3.0) {
            jTextFieldPorcentaje.setText("89 %");
        }
        if (resultadofinal == 3.1) {
            jTextFieldPorcentaje.setText("91 %");
        }
        if (resultadofinal == 3.2) {
            jTextFieldPorcentaje.setText("92 %");
        }

        jTextFieldResultado.setText(bigDecimal.toString());
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcercadeActionPerformed
        Acercade tab = new Acercade();
        tab.setVisible(true);
        this.dispose(); // abre la Ventana de nuestros datos
    }//GEN-LAST:event_jButtonAcercadeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Conceptos tab = new Conceptos();
        tab.setVisible(true);
        this.dispose();             // Abre los conceptos basicos

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldPorcentaje.setText("");
        jTextFieldSimboloDos.setText("");
        jTextFieldSimboloUno.setText("");
        jTextFieldResultado.setText("");   //limpia todas las texField
        jTextFieldSimboloTres.setText("");

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Electronegatividad_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Electronegatividad_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Electronegatividad_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Electronegatividad_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Electronegatividad_Frame_01().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAcercade;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldPorcentaje;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldSimboloCuatro;
    private javax.swing.JTextField jTextFieldSimboloDos;
    private javax.swing.JTextField jTextFieldSimboloTres;
    private javax.swing.JTextField jTextFieldSimboloUno;
    // End of variables declaration//GEN-END:variables
}
