/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electronegatividad;
import java.applet.AudioClip;
import static java.lang.Thread.sleep;
/**
 *
 * @author jondalar
 */
public class tabla extends javax.swing.JFrame {

    /**
     * Creates new form tabla
     */
    public tabla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        C = new javax.swing.JButton();
        LI = new javax.swing.JButton();
        BE = new javax.swing.JButton();
        F = new javax.swing.JButton();
        B = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        CL = new javax.swing.JButton();
        NA = new javax.swing.JButton();
        SI = new javax.swing.JButton();
        MG = new javax.swing.JButton();
        AL = new javax.swing.JButton();
        S = new javax.swing.JButton();
        RA = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        PT = new javax.swing.JButton();
        HF = new javax.swing.JButton();
        TA = new javax.swing.JButton();
        W = new javax.swing.JButton();
        RE = new javax.swing.JButton();
        OS = new javax.swing.JButton();
        HG = new javax.swing.JButton();
        AT = new javax.swing.JButton();
        AU = new javax.swing.JButton();
        IR = new javax.swing.JButton();
        IN = new javax.swing.JButton();
        K = new javax.swing.JButton();
        CA = new javax.swing.JButton();
        SC = new javax.swing.JButton();
        TI = new javax.swing.JButton();
        V = new javax.swing.JButton();
        CR = new javax.swing.JButton();
        MN = new javax.swing.JButton();
        FE = new javax.swing.JButton();
        CO = new javax.swing.JButton();
        NI = new javax.swing.JButton();
        CU = new javax.swing.JButton();
        ZN = new javax.swing.JButton();
        GA = new javax.swing.JButton();
        BR = new javax.swing.JButton();
        P = new javax.swing.JButton();
        GE = new javax.swing.JButton();
        AS = new javax.swing.JButton();
        SE = new javax.swing.JButton();
        PB = new javax.swing.JButton();
        BI = new javax.swing.JButton();
        PO = new javax.swing.JButton();
        FR = new javax.swing.JButton();
        RB = new javax.swing.JButton();
        SR = new javax.swing.JButton();
        ZR = new javax.swing.JButton();
        NB = new javax.swing.JButton();
        MO = new javax.swing.JButton();
        TC = new javax.swing.JButton();
        RU = new javax.swing.JButton();
        RH = new javax.swing.JButton();
        PD = new javax.swing.JButton();
        AG = new javax.swing.JButton();
        TL = new javax.swing.JButton();
        CD = new javax.swing.JButton();
        SN = new javax.swing.JButton();
        SB = new javax.swing.JButton();
        TE = new javax.swing.JButton();
        I = new javax.swing.JButton();
        CS = new javax.swing.JButton();
        BA = new javax.swing.JButton();
        H = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 100, 40));

        C.setContentAreaFilled(false);
        C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 40, 60));

        LI.setContentAreaFilled(false);
        LI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LIMouseClicked(evt);
            }
        });
        getContentPane().add(LI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 60));

        BE.setContentAreaFilled(false);
        BE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEMouseClicked(evt);
            }
        });
        getContentPane().add(BE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 60));

        F.setContentAreaFilled(false);
        F.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
        });
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 40, 60));

        B.setContentAreaFilled(false);
        B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMouseClicked(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 40, 60));

        N.setContentAreaFilled(false);
        N.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NMouseClicked(evt);
            }
        });
        getContentPane().add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 40, 60));

        O.setContentAreaFilled(false);
        O.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMouseClicked(evt);
            }
        });
        getContentPane().add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 40, 60));

        CL.setContentAreaFilled(false);
        CL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLMouseClicked(evt);
            }
        });
        getContentPane().add(CL, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 40, 70));

        NA.setContentAreaFilled(false);
        NA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NAMouseEntered(evt);
            }
        });
        getContentPane().add(NA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 40, 70));

        SI.setContentAreaFilled(false);
        SI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIMouseClicked(evt);
            }
        });
        getContentPane().add(SI, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 40, 70));

        MG.setContentAreaFilled(false);
        MG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MGMouseClicked(evt);
            }
        });
        getContentPane().add(MG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 40, 70));

        AL.setContentAreaFilled(false);
        AL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ALMouseClicked(evt);
            }
        });
        getContentPane().add(AL, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 40, 70));

        S.setContentAreaFilled(false);
        S.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SMouseClicked(evt);
            }
        });
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 40, 70));

        RA.setContentAreaFilled(false);
        RA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RAMouseClicked(evt);
            }
        });
        getContentPane().add(RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 40, 60));

        Y.setContentAreaFilled(false);
        Y.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YMouseClicked(evt);
            }
        });
        getContentPane().add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 40, 60));

        PT.setContentAreaFilled(false);
        PT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PTMouseClicked(evt);
            }
        });
        getContentPane().add(PT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 40, 60));

        HF.setContentAreaFilled(false);
        HF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HFMouseClicked(evt);
            }
        });
        getContentPane().add(HF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 40, 60));

        TA.setContentAreaFilled(false);
        TA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TAMouseClicked(evt);
            }
        });
        getContentPane().add(TA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 40, 60));

        W.setContentAreaFilled(false);
        W.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        W.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WMouseClicked(evt);
            }
        });
        getContentPane().add(W, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 400, 40, 60));

        RE.setContentAreaFilled(false);
        RE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REMouseClicked(evt);
            }
        });
        getContentPane().add(RE, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 400, 40, 60));

        OS.setContentAreaFilled(false);
        OS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OSMouseClicked(evt);
            }
        });
        getContentPane().add(OS, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 400, 40, 60));

        HG.setContentAreaFilled(false);
        HG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HGMouseClicked(evt);
            }
        });
        getContentPane().add(HG, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 50, 60));

        AT.setContentAreaFilled(false);
        AT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ATMouseClicked(evt);
            }
        });
        getContentPane().add(AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 40, 60));

        AU.setContentAreaFilled(false);
        AU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AUMouseClicked(evt);
            }
        });
        getContentPane().add(AU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 50, 60));

        IR.setContentAreaFilled(false);
        IR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IRMouseClicked(evt);
            }
        });
        getContentPane().add(IR, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 400, 40, 60));

        IN.setContentAreaFilled(false);
        IN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INMouseClicked(evt);
            }
        });
        getContentPane().add(IN, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 40, 60));

        K.setContentAreaFilled(false);
        K.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KMouseClicked(evt);
            }
        });
        getContentPane().add(K, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 60));

        CA.setContentAreaFilled(false);
        CA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAMouseClicked(evt);
            }
        });
        getContentPane().add(CA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 40, 60));

        SC.setContentAreaFilled(false);
        SC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCMouseClicked(evt);
            }
        });
        getContentPane().add(SC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, 60));

        TI.setContentAreaFilled(false);
        TI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIMouseClicked(evt);
            }
        });
        getContentPane().add(TI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 40, 60));

        V.setContentAreaFilled(false);
        V.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VMouseClicked(evt);
            }
        });
        getContentPane().add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 40, 60));

        CR.setContentAreaFilled(false);
        CR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CRMouseClicked(evt);
            }
        });
        getContentPane().add(CR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 40, 60));

        MN.setContentAreaFilled(false);
        MN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNMouseClicked(evt);
            }
        });
        getContentPane().add(MN, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 250, 40, 60));

        FE.setContentAreaFilled(false);
        FE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FEMouseClicked(evt);
            }
        });
        getContentPane().add(FE, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 250, 40, 60));

        CO.setContentAreaFilled(false);
        CO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COMouseClicked(evt);
            }
        });
        getContentPane().add(CO, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 250, 40, 60));

        NI.setContentAreaFilled(false);
        NI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NIMouseClicked(evt);
            }
        });
        getContentPane().add(NI, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 40, 60));

        CU.setContentAreaFilled(false);
        CU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CUMouseClicked(evt);
            }
        });
        getContentPane().add(CU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 50, 60));

        ZN.setContentAreaFilled(false);
        ZN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ZN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZNMouseClicked(evt);
            }
        });
        getContentPane().add(ZN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 50, 60));

        GA.setContentAreaFilled(false);
        GA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GAMouseClicked(evt);
            }
        });
        getContentPane().add(GA, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 40, 60));

        BR.setContentAreaFilled(false);
        BR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRMouseClicked(evt);
            }
        });
        getContentPane().add(BR, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 40, 60));

        P.setContentAreaFilled(false);
        P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMouseClicked(evt);
            }
        });
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 40, 70));

        GE.setContentAreaFilled(false);
        GE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GEMouseClicked(evt);
            }
        });
        getContentPane().add(GE, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 40, 60));

        AS.setContentAreaFilled(false);
        AS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ASMouseClicked(evt);
            }
        });
        getContentPane().add(AS, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 40, 60));

        SE.setContentAreaFilled(false);
        SE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SEMouseClicked(evt);
            }
        });
        getContentPane().add(SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 40, 60));

        PB.setContentAreaFilled(false);
        PB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PBMouseClicked(evt);
            }
        });
        getContentPane().add(PB, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 40, 60));

        BI.setContentAreaFilled(false);
        BI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BIMouseClicked(evt);
            }
        });
        getContentPane().add(BI, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 40, 60));

        PO.setContentAreaFilled(false);
        PO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                POMouseClicked(evt);
            }
        });
        getContentPane().add(PO, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, 40, 60));

        FR.setContentAreaFilled(false);
        FR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FRMouseClicked(evt);
            }
        });
        getContentPane().add(FR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 40, 60));

        RB.setContentAreaFilled(false);
        RB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBMouseClicked(evt);
            }
        });
        getContentPane().add(RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 40, 60));

        SR.setContentAreaFilled(false);
        SR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SRMouseClicked(evt);
            }
        });
        getContentPane().add(SR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 40, 60));

        ZR.setContentAreaFilled(false);
        ZR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ZR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZRMouseClicked(evt);
            }
        });
        getContentPane().add(ZR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 40, 60));

        NB.setContentAreaFilled(false);
        NB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NBMouseClicked(evt);
            }
        });
        getContentPane().add(NB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 40, 60));

        MO.setContentAreaFilled(false);
        MO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MOMouseClicked(evt);
            }
        });
        getContentPane().add(MO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 40, 60));

        TC.setContentAreaFilled(false);
        TC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TCMouseClicked(evt);
            }
        });
        getContentPane().add(TC, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 320, 40, 60));

        RU.setContentAreaFilled(false);
        RU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUMouseClicked(evt);
            }
        });
        getContentPane().add(RU, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 320, 40, 60));

        RH.setContentAreaFilled(false);
        RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RHMouseClicked(evt);
            }
        });
        getContentPane().add(RH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 40, 60));

        PD.setContentAreaFilled(false);
        PD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PDMouseClicked(evt);
            }
        });
        getContentPane().add(PD, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 320, 40, 60));

        AG.setContentAreaFilled(false);
        AG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AGMouseClicked(evt);
            }
        });
        getContentPane().add(AG, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 50, 60));

        TL.setContentAreaFilled(false);
        TL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TLMouseClicked(evt);
            }
        });
        getContentPane().add(TL, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 40, 60));

        CD.setContentAreaFilled(false);
        CD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CDMouseClicked(evt);
            }
        });
        getContentPane().add(CD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 50, 60));

        SN.setContentAreaFilled(false);
        SN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNMouseClicked(evt);
            }
        });
        getContentPane().add(SN, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 40, 60));

        SB.setContentAreaFilled(false);
        SB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SBMouseClicked(evt);
            }
        });
        getContentPane().add(SB, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 40, 60));

        TE.setContentAreaFilled(false);
        TE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEMouseClicked(evt);
            }
        });
        getContentPane().add(TE, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 40, 60));

        I.setContentAreaFilled(false);
        I.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMouseClicked(evt);
            }
        });
        getContentPane().add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 40, 60));

        CS.setContentAreaFilled(false);
        CS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSMouseClicked(evt);
            }
        });
        getContentPane().add(CS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 40, 60));

        BA.setContentAreaFilled(false);
        BA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BAMouseClicked(evt);
            }
        });
        getContentPane().add(BA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 40, 60));

        H.setContentAreaFilled(false);
        H.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HMouseClicked(evt);
            }
        });
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("TABLA DE ELECTRONEGATIVIDAD ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronegatividad/imagen/TBL.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1020, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronegatividad/imagen/Captura de pantalla de 2018-11-15 21-49-01.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electronegatividad/imagen/Captura de pantalla de 2018-11-15 21-49-01.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Electronegatividad_Frame_01 tab = new Electronegatividad_Frame_01();
        tab.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/H"
            + ".wav"));
    sonido.play();        
    }//GEN-LAST:event_HMouseClicked

    private void LIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/LI"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_LIMouseClicked

    private void BEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/BE"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_BEMouseClicked

    private void BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/B"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_BMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/C"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CMouseClicked

    private void NMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/N"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_NMouseClicked

    private void OMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/O"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_OMouseClicked

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/F"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_FMouseClicked

    private void NAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NAMouseEntered
    
    }//GEN-LAST:event_NAMouseEntered

    private void MGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MGMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/MG"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_MGMouseClicked

    private void ALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AL"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_ALMouseClicked

    private void SIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/SI"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SIMouseClicked

    private void PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/P"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_PMouseClicked

    private void SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/S"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SMouseClicked

    private void CLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CL"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CLMouseClicked

    private void KMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/K"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_KMouseClicked

    private void CAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CA"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CAMouseClicked

    private void SCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/SC"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SCMouseClicked

    private void TIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/TI"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_TIMouseClicked

    private void VMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/V"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_VMouseClicked

    private void CRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CR"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CRMouseClicked

    private void MNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/MN"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_MNMouseClicked

    private void FEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FEMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/FE"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_FEMouseClicked

    private void COMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CO"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_COMouseClicked

    private void NIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NIMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/NI"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_NIMouseClicked

    private void CUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CU"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CUMouseClicked

    private void ZNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZNMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/ZN"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_ZNMouseClicked

    private void GAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GAMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/GA"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_GAMouseClicked

    private void GEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GEMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/GE"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_GEMouseClicked

    private void ASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ASMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AS"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_ASMouseClicked

    private void SEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/SE"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SEMouseClicked

    private void BRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/BR"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_BRMouseClicked

    private void RBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/RB"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_RBMouseClicked

    private void SRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SRMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/SR"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SRMouseClicked

    private void YMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/Y"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_YMouseClicked

    private void ZRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZRMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/ZR"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_ZRMouseClicked

    private void NBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NBMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/NB"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_NBMouseClicked

    private void MOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/MO"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_MOMouseClicked

    private void TCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TCMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/TC"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_TCMouseClicked

    private void RUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/RU"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_RUMouseClicked

    private void RHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RHMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/RH"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_RHMouseClicked

    private void PDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/PD"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_PDMouseClicked

    private void AGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AG"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_AGMouseClicked

    private void CDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CDMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CD"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CDMouseClicked

    private void INMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/IN"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_INMouseClicked

    private void SNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/SN"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SNMouseClicked

    private void SBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/SB"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_SBMouseClicked

    private void TEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/TE"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_TEMouseClicked

    private void IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/I"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_IMouseClicked

    private void CSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CS"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_CSMouseClicked

    private void BAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/BA"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_BAMouseClicked

    private void HFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HFMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/HF"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_HFMouseClicked

    private void TAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TAMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/TA"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_TAMouseClicked

    private void WMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/W"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_WMouseClicked

    private void REMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/RE"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_REMouseClicked

    private void OSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OSMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/OS"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_OSMouseClicked

    private void IRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IRMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/IR"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_IRMouseClicked

    private void PTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PTMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/PT"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_PTMouseClicked

    private void AUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AU"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_AUMouseClicked

    private void HGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HGMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/HG"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_HGMouseClicked

    private void TLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TLMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/TL"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_TLMouseClicked

    private void PBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PBMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/PB"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_PBMouseClicked

    private void BIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BIMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/BI"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_BIMouseClicked

    private void POMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/PO"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_POMouseClicked

    private void ATMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AT"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_ATMouseClicked

    private void FRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FRMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/FR"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_FRMouseClicked

    private void RAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RAMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/RA"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_RAMouseClicked

    private void NAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NAMouseClicked
    AudioClip sonido;
    sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Audios/NA"
            + ".wav"));
    sonido.play();  
    }//GEN-LAST:event_NAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AG;
    private javax.swing.JButton AL;
    private javax.swing.JButton AS;
    private javax.swing.JButton AT;
    private javax.swing.JButton AU;
    private javax.swing.JButton B;
    private javax.swing.JButton BA;
    private javax.swing.JButton BE;
    private javax.swing.JButton BI;
    private javax.swing.JButton BR;
    private javax.swing.JButton C;
    private javax.swing.JButton CA;
    private javax.swing.JButton CD;
    private javax.swing.JButton CL;
    private javax.swing.JButton CO;
    private javax.swing.JButton CR;
    private javax.swing.JButton CS;
    private javax.swing.JButton CU;
    private javax.swing.JButton F;
    private javax.swing.JButton FE;
    private javax.swing.JButton FR;
    private javax.swing.JButton GA;
    private javax.swing.JButton GE;
    private javax.swing.JButton H;
    private javax.swing.JButton HF;
    private javax.swing.JButton HG;
    private javax.swing.JButton I;
    private javax.swing.JButton IN;
    private javax.swing.JButton IR;
    private javax.swing.JButton K;
    private javax.swing.JButton LI;
    private javax.swing.JButton MG;
    private javax.swing.JButton MN;
    private javax.swing.JButton MO;
    private javax.swing.JButton N;
    private javax.swing.JButton NA;
    private javax.swing.JButton NB;
    private javax.swing.JButton NI;
    private javax.swing.JButton O;
    private javax.swing.JButton OS;
    private javax.swing.JButton P;
    private javax.swing.JButton PB;
    private javax.swing.JButton PD;
    private javax.swing.JButton PO;
    private javax.swing.JButton PT;
    private javax.swing.JButton RA;
    private javax.swing.JButton RB;
    private javax.swing.JButton RE;
    private javax.swing.JButton RH;
    private javax.swing.JButton RU;
    private javax.swing.JButton S;
    private javax.swing.JButton SB;
    private javax.swing.JButton SC;
    private javax.swing.JButton SE;
    private javax.swing.JButton SI;
    private javax.swing.JButton SN;
    private javax.swing.JButton SR;
    private javax.swing.JButton TA;
    private javax.swing.JButton TC;
    private javax.swing.JButton TE;
    private javax.swing.JButton TI;
    private javax.swing.JButton TL;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton Y;
    private javax.swing.JButton ZN;
    private javax.swing.JButton ZR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
